- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
              title: Ciechanow
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
              title: Samwho
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed
            - url: https://rss.arxiv.org/rss/cs.LG
              title: Arxiv CS -- Machine Learning

    - size: full
      widgets:
        - type: search
          search-engine: google
          bangs:
          - title: YouTube
            shortcut: "!yt"
            url: https://www.youtube.com/results?search_query={QUERY}

        - type: group
          widgets:
            - type: rss
              title: Hacker News 
              cache: 12h
              feeds: 
                - url: https://news.ycombinator.com/rss
                  title: Hacker News
            - type: rss
              title: TDS
              cache: 12h
              feeds:
                - url: https://towardsdatascience.com/feed/
                  title: Towards Data Science
            - type: rss
              title: Lesswrong
              cache: 12h
              feeds:
                - url: https://www.lesswrong.com/feed.xml?view=curated-rss
                  title: Lesswrong
            - type: rss
              title: GAI
              cache: 12h
              feeds:
                - url: https://blog.google/technology/ai/rss/
                  title: Google AI
            - type: rss
              title: MIT
              cache: 12h
              feeds:
                - url: https://news.mit.edu/rss/topic/machine-learning
                  title: MIT
            - type: rss
              title: AWS
              cache: 12h
              feeds:
                - url: https://aws.amazon.com/blogs/machine-learning/feed/
                  title: AWS

        - type: bookmarks
          groups:
            
          - title: Reading
            color: 60 70 40
            links:
              - title: Lesswrong
                url: https://www.lesswrong.com/
          - title: Social
            color: 200 50 50
            links:
              - title: Reddit
                url: https://www.reddit.com/
              - title: Twitter
                url: https://twitter.com/
              - title: Instagram
                url: https://www.instagram.com/
    
          
    - size: small
      widgets:
        - type: weather
          location: Dortmund, Germany
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: to-do

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing
